import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 min-h-screen`}
      >
        <div className="mx-auto max-w-7xl flex flex-col min-h-screen">
          <header className="p-4 md:p-6 bg-white shadow-sm sticky top-0 z-10 flex items-center gap-4">
            <h1 className="text-xl font-semibold tracking-tight">
              Patient Dashboard
            </h1>
          </header>
          <div className="flex-1 p-4 md:p-6">{children}</div>
          <footer className="p-4 text-center text-xs text-gray-500">
            © {new Date().getFullYear()} Patient Records
          </footer>
        </div>
      </body>
    </html>
  );
}
