import { TopNav } from "@/@components/layout/TopNav";
import type { Metadata } from "next";
import "./globals.css";
import { t } from "@/lib/i18n";

// Fallback font variables for when Google Fonts are not available
const geistSans = {
  variable: "--font-geist-sans",
};

const geistMono = {
  variable: "--font-geist-mono",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <div className="mx-auto max-w-[1568px] flex flex-col min-h-screen px-3 md:px-6 py-3 gap-4">
          <div className="sticky top-3 z-20">
            <TopNav />
          </div>
          <div className="flex-1 pb-6">{children}</div>
          <footer className="p-4 text-center text-xs text-gray-500">
            {t('footer.copyright', 'en', { year: new Date().getFullYear() })}
          </footer>
        </div>
      </body>
    </html>
  );
}
